### PR TITLE
Add flood data in new 'disasters' section

### PR DESCRIPTION
**Pull request by crispg72**
This pr adds the flood data from https://github.com/Code4Nepal/nepalmap_app/issues/186

I've created a new section for 'Disasters' as you suggested, let me know whether this is the kind of thing you were thinking of.

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@crispg72

Thank you. I am traveling but will do my best to review Sunday evening or Monday evening

**Comment by cliftonmcintosh** [comment]
@crispg72 

Looks good.

@ravinepal 

Is this flood deaths for  the 2017 floods or for floods in other time periods as well? I think we should adjust the description to specify which.

**Comment by ravinepal** [comment]
Hi @cliftonmcintosh, thanks for checking. looks like @crispg72 used [data](Here's the updated flood, landslides data from 2010--08-08 to 2017-08-30 - https://docs.google.com/spreadsheets/d/1WGEsVT0eiWnE34uA9-z3a4cKStcYhCvo_3ANiVzZTYk/edit?ts=59c8020a#gid=617759520). In that case, we should adjust the description in bold along the lines of

Total deaths due to Flood, Heavy Rainfall and Landslide from March 2011 to August 2017. 

This is the primary source and we should link it to: http://drrportal.gov.np/

**Comment by cliftonmcintosh** [comment]
@ravinepal 

https://github.com/Code4Nepal/nepalmap_app/pull/220 updates the sources.

**Pull request merged**
