### PR TITLE
Update sources and descriptions for disaster data

### PR DESCRIPTION
**Pull request by cliftonmcintosh**
As per @ravinepal's comments on #206 

nepal-disaster-source-update

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Was the update incorrect? Did you mean to merge instead of close?

**Comment by ravinepal** [comment]
hey @cliftonmcintosh - sorry about that. i should avoid doing work when i have jet lag :)

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Do the changes in this PR fit what you wanted when you mentioned updating the links? If so, please merge, and I will get the updates onto the server.

**Comment by cliftonmcintosh** [comment]
@ravinepal 

Would you have time to review this pull request and merge if it looks good?

Thanks.

**Comment by ravinepal** [comment]
Sorry about the delay. Was offline and traveling.

**Pull request merged**
