### PR TITLE
Data scrape/coffee by district

### PR DESCRIPTION
**Pull request by robalaban**
Added parsed CSV file for Coffee production table. 

Requirements for running the scrapper are: 

1) Java (7 or 8), tested on OSX
2) PyPDF2 `pip install PyPDF2`
3) tabula `pip install tabula-py`

### CODE REVIEW

**Comment by ravinepal** [comment]
thanks, @robalaban! really appreciate your help! i'll review soon. looks like we don't have data for 50 districts. we might have to add names of those districts and say "N/A" as we need info for all districts. Let me double check and get back to you.

**Comment by cliftonmcintosh** [comment]
@robalaban 

Would you be willing to submit this pull request against our [data repository](https://github.com/Code4Nepal/data) instead? This would allow us to house the data before importing and sharing it in NepalMap. If you do this, we would also welcome the submission of your script as documentation for how the data was prepared.

An alternative would be to complete the coffee by district task fully for NepalMap. We would welcome that as well. Here is a wiki page for NepalMap giving guidance on how to complete the tasks needed for integrating a data set into NepalMap: https://github.com/Code4Nepal/nepalmap_app/wiki/Collecting-and-visualizing-data-in-NepalMap

**Comment by ravinepal** [comment]
thanks, @cliftonmcintosh! @robalaban - pls consider submitting the pull request to data repository as Cliff suggested.

**Comment by cliftonmcintosh** [comment]
@robalaban 

Thank you for your contribution. I am closing this PR in favor of storing the data in the data project instead.

Data has been added here: https://github.com/Code4Nepal/data/blob/master/datasets/agriculture/coffee.csv

**Pull request closed without merging**
