### PR TITLE
open a pdf in new Window issue #96

### PR DESCRIPTION
**Pull request by luizfelipetx**
Hi , this is the fix to issue #96 , to open a pdf link on a new window/tab ( your browser will choose between tab or window ) .
I hope that can help.  :)

### CODE REVIEW

**Comment by clifton-mcintosh** [comment]
@luizfelipetx 

Thanks. Would you be willing to amend your pull request so that the text says "Nepal Human Development Report 2014 (PDF)" to fulfill the other part of #96 ?

**Comment by luizfelipetx** [comment]
@clifton-mcintosh  sure. one minute.

**Comment by luizfelipetx** [comment]
@clifton-mcintosh  correct ? 
https://github.com/Code4Nepal/nepalmap_app/pull/97/commits/a2f01ee153fa4eaec7206a85ec60690f4597a7a8

**Comment by cliftonmcintosh** [comment]
Thanks, @luizfelipetx

**Comment by ravinepal** [comment]
@luizfelipetx hi! thank you for your help! the PDF still doesn't open in a new window. could you pls double check?

**Comment by cliftonmcintosh** [comment]
@ravinepal It opens in a new window for me

**Pull request merged**
