### PR TITLE
fix the installation info

### PR DESCRIPTION
**Pull request by techgaun**
I had to exclude geography.sql from initial data seeding, run the migration and then import geography.sql. Otherwise, it would throw error saying `relation "wazimap_geography" already exists`. also added steps on fresh ubuntu 16.04 install I followed so that install of psycopg2 and gdal would not complain.

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@techgaun 

Thank you for catching that. There are some issues with how Wazimap handles `manage.py migrate`. "SimpleTable" entries (like this project's [lifeexpectancy](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/tables.py#L40) and [per_capita_income](https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/tables.py#L49) SimpleTables) seem to require that the tables already exist (There's an [issue](https://github.com/Code4SA/wazimap/issues/60) open for this.) Because I had already run the initial wazimap migration, I did not realize the workflow would fail on the wazimap_geography migration.

I would like to suggest an alternative to your workaround: a sub-directory of sql files that should be run before the migrations can succeed. So the workflow would go something like this:

- move `lifeexpectancy.sql` and `income.sql` into a directory at `sql/simpletables`
- run the sql in `sql/simpletables/*sql` to create the tables that must be created before migrations can succeed
- run `manage.py migrate`
- run the sql in `sql/*.sql` to fill in the other tables

Does that seem sensible? If so, I can update the project or if you would be interested in making the change, that's fine, too.

**Comment by cliftonmcintosh** [comment]
The other thing to note is that there are more detailed installation instructions on the wiki [here](https://github.com/Code4Nepal/nepalmap_app/wiki/Extended-Description-for-Local-Installation). These include OS-specific suggestions. Perhaps we should either link to those directions in the readme or build on your additions in the readme file so that we don't have duplicate instructions for OS-specific issues.

**Comment by techgaun** [comment]
@cliftonmcintosh thanks for the response. I agree with the organization you mentioned about the migration steps. I updated accordingly.

As for detailed instruction, I personally like having install section within readme (or INSTALL.md if its little involving than wiki) but as long as its linked from readme, putting in wiki is also fine. I didn't know that there's a wiki but I may have missed a link to it.

**Comment by cliftonmcintosh** [comment]
Thanks for the update! A `.DS_Store` file got included. Would you mind removing that prior to a merge?

**Comment by techgaun** [comment]
@cliftonmcintosh nope, I removed it. it might have appeared otherwise. It was already in the repo so I also added it in gitignore.

**Comment by cliftonmcintosh** [comment]
@techgaun You're right. I misread the diff. My apologies, and thanks for removing it.

**Comment by techgaun** [comment]
awesome thanks @cliftonmcintosh

**Pull request merged**
